-- Initial content for the shared vehicle catalog (public.vehicle_makes / public.vehicle_models).
--
-- Generated from infrastructure/database/.../VehicleSeedData.kt's RAW_SEED, using the exact
-- same id-slug algorithm, so a freshly-onboarded Supabase project and a freshly-installed
-- app agree on every row's id from the very first refresh. Run this once, after
-- 20260829120000_vehicle_catalog.sql, in the SQL editor. Safe to re-run: every insert is
-- ON CONFLICT DO NOTHING, matching the local seed's own INSERT OR IGNORE semantics.
--
-- To add more cars later: append rows here (or write a fresh INSERT block) and run it — no
-- need to touch the app at all. VehicleCatalogRefresher picks up new rows on the next
-- background refresh.

insert into public.vehicle_makes (id, name, display_order) values
('make-maruti-suzuki', 'Maruti Suzuki', 0),
('make-hyundai', 'Hyundai', 1),
('make-tata', 'Tata', 2),
('make-mahindra', 'Mahindra', 3),
('make-toyota', 'Toyota', 4),
('make-kia', 'Kia', 5),
('make-honda', 'Honda', 6),
('make-renault', 'Renault', 7),
('make-volkswagen', 'Volkswagen', 8),
('make-skoda', 'Skoda', 9),
('make-mg', 'MG', 10),
('make-nissan', 'Nissan', 11),
('make-jeep', 'Jeep', 12),
('make-citroen', 'Citroen', 13),
('make-byd', 'BYD', 14),
('make-mercedes-benz', 'Mercedes-Benz', 15),
('make-bmw', 'BMW', 16),
('make-audi', 'Audi', 17),
('make-volvo', 'Volvo', 18),
('make-land-rover', 'Land Rover', 19),
('make-jaguar', 'Jaguar', 20),
('make-lexus', 'Lexus', 21),
('make-mini', 'MINI', 22),
('make-porsche', 'Porsche', 23),
('make-isuzu', 'Isuzu', 24),
('make-force-motors', 'Force Motors', 25),
('make-mitsubishi', 'Mitsubishi', 26),
('make-fiat', 'Fiat', 27),
('make-chevrolet', 'Chevrolet', 28),
('make-datsun', 'Datsun', 29),
('make-premier', 'Premier', 30)
on conflict (id) do nothing;

insert into public.vehicle_models (id, make_id, name, variant, display_order) values
('model-maruti-suzuki-swift', 'make-maruti-suzuki', 'Swift', null, 0),
('model-maruti-suzuki-swift-lxi', 'make-maruti-suzuki', 'Swift', 'LXI', 1),
('model-maruti-suzuki-swift-vxi', 'make-maruti-suzuki', 'Swift', 'VXI', 2),
('model-maruti-suzuki-swift-zxi', 'make-maruti-suzuki', 'Swift', 'ZXI', 3),
('model-maruti-suzuki-swift-zxi-plus', 'make-maruti-suzuki', 'Swift', 'ZXI+', 4),
('model-maruti-suzuki-baleno', 'make-maruti-suzuki', 'Baleno', null, 100),
('model-maruti-suzuki-baleno-sigma', 'make-maruti-suzuki', 'Baleno', 'Sigma', 101),
('model-maruti-suzuki-baleno-delta', 'make-maruti-suzuki', 'Baleno', 'Delta', 102),
('model-maruti-suzuki-baleno-zeta', 'make-maruti-suzuki', 'Baleno', 'Zeta', 103),
('model-maruti-suzuki-baleno-alpha', 'make-maruti-suzuki', 'Baleno', 'Alpha', 104),
('model-maruti-suzuki-dzire', 'make-maruti-suzuki', 'Dzire', null, 200),
('model-maruti-suzuki-dzire-lxi', 'make-maruti-suzuki', 'Dzire', 'LXI', 201),
('model-maruti-suzuki-dzire-vxi', 'make-maruti-suzuki', 'Dzire', 'VXI', 202),
('model-maruti-suzuki-dzire-zxi', 'make-maruti-suzuki', 'Dzire', 'ZXI', 203),
('model-maruti-suzuki-dzire-zxi-plus', 'make-maruti-suzuki', 'Dzire', 'ZXI+', 204),
('model-maruti-suzuki-wagonr', 'make-maruti-suzuki', 'WagonR', null, 300),
('model-maruti-suzuki-wagonr-lxi', 'make-maruti-suzuki', 'WagonR', 'LXI', 301),
('model-maruti-suzuki-wagonr-vxi', 'make-maruti-suzuki', 'WagonR', 'VXI', 302),
('model-maruti-suzuki-wagonr-zxi', 'make-maruti-suzuki', 'WagonR', 'ZXI', 303),
('model-maruti-suzuki-wagonr-zxi-plus', 'make-maruti-suzuki', 'WagonR', 'ZXI+', 304),
('model-maruti-suzuki-brezza', 'make-maruti-suzuki', 'Brezza', null, 400),
('model-maruti-suzuki-brezza-lxi', 'make-maruti-suzuki', 'Brezza', 'LXI', 401),
('model-maruti-suzuki-brezza-vxi', 'make-maruti-suzuki', 'Brezza', 'VXI', 402),
('model-maruti-suzuki-brezza-zxi', 'make-maruti-suzuki', 'Brezza', 'ZXI', 403),
('model-maruti-suzuki-brezza-zxi-plus', 'make-maruti-suzuki', 'Brezza', 'ZXI+', 404),
('model-maruti-suzuki-ertiga', 'make-maruti-suzuki', 'Ertiga', null, 500),
('model-maruti-suzuki-ertiga-lxi', 'make-maruti-suzuki', 'Ertiga', 'LXI', 501),
('model-maruti-suzuki-ertiga-vxi', 'make-maruti-suzuki', 'Ertiga', 'VXI', 502),
('model-maruti-suzuki-ertiga-zxi', 'make-maruti-suzuki', 'Ertiga', 'ZXI', 503),
('model-maruti-suzuki-ertiga-zxi-plus', 'make-maruti-suzuki', 'Ertiga', 'ZXI+', 504),
('model-maruti-suzuki-alto-k10', 'make-maruti-suzuki', 'Alto K10', null, 600),
('model-maruti-suzuki-alto-k10-std', 'make-maruti-suzuki', 'Alto K10', 'STD', 601),
('model-maruti-suzuki-alto-k10-lxi', 'make-maruti-suzuki', 'Alto K10', 'LXI', 602),
('model-maruti-suzuki-alto-k10-vxi', 'make-maruti-suzuki', 'Alto K10', 'VXI', 603),
('model-maruti-suzuki-alto-k10-vxi-plus', 'make-maruti-suzuki', 'Alto K10', 'VXI+', 604),
('model-maruti-suzuki-fronx', 'make-maruti-suzuki', 'Fronx', null, 700),
('model-maruti-suzuki-fronx-sigma', 'make-maruti-suzuki', 'Fronx', 'Sigma', 701),
('model-maruti-suzuki-fronx-delta', 'make-maruti-suzuki', 'Fronx', 'Delta', 702),
('model-maruti-suzuki-fronx-delta-plus', 'make-maruti-suzuki', 'Fronx', 'Delta+', 703),
('model-maruti-suzuki-fronx-zeta', 'make-maruti-suzuki', 'Fronx', 'Zeta', 704),
('model-maruti-suzuki-fronx-alpha', 'make-maruti-suzuki', 'Fronx', 'Alpha', 705),
('model-maruti-suzuki-grand-vitara', 'make-maruti-suzuki', 'Grand Vitara', null, 800),
('model-maruti-suzuki-grand-vitara-sigma', 'make-maruti-suzuki', 'Grand Vitara', 'Sigma', 801),
('model-maruti-suzuki-grand-vitara-delta', 'make-maruti-suzuki', 'Grand Vitara', 'Delta', 802),
('model-maruti-suzuki-grand-vitara-zeta', 'make-maruti-suzuki', 'Grand Vitara', 'Zeta', 803),
('model-maruti-suzuki-grand-vitara-alpha', 'make-maruti-suzuki', 'Grand Vitara', 'Alpha', 804),
('model-maruti-suzuki-eeco', 'make-maruti-suzuki', 'Eeco', null, 900),
('model-maruti-suzuki-eeco-std', 'make-maruti-suzuki', 'Eeco', 'STD', 901),
('model-maruti-suzuki-eeco-5-str', 'make-maruti-suzuki', 'Eeco', '5 STR', 902),
('model-maruti-suzuki-celerio', 'make-maruti-suzuki', 'Celerio', null, 1000),
('model-maruti-suzuki-celerio-lxi', 'make-maruti-suzuki', 'Celerio', 'LXI', 1001),
('model-maruti-suzuki-celerio-vxi', 'make-maruti-suzuki', 'Celerio', 'VXI', 1002),
('model-maruti-suzuki-celerio-zxi', 'make-maruti-suzuki', 'Celerio', 'ZXI', 1003),
('model-maruti-suzuki-celerio-zxi-plus', 'make-maruti-suzuki', 'Celerio', 'ZXI+', 1004),
('model-maruti-suzuki-s-presso', 'make-maruti-suzuki', 'S-Presso', null, 1100),
('model-maruti-suzuki-s-presso-std', 'make-maruti-suzuki', 'S-Presso', 'STD', 1101),
('model-maruti-suzuki-s-presso-lxi', 'make-maruti-suzuki', 'S-Presso', 'LXI', 1102),
('model-maruti-suzuki-s-presso-vxi', 'make-maruti-suzuki', 'S-Presso', 'VXI', 1103),
('model-maruti-suzuki-s-presso-vxi-plus', 'make-maruti-suzuki', 'S-Presso', 'VXI+', 1104),
('model-hyundai-i20', 'make-hyundai', 'i20', null, 0),
('model-hyundai-i20-era', 'make-hyundai', 'i20', 'Era', 1),
('model-hyundai-i20-magna', 'make-hyundai', 'i20', 'Magna', 2),
('model-hyundai-i20-sportz', 'make-hyundai', 'i20', 'Sportz', 3),
('model-hyundai-i20-asta', 'make-hyundai', 'i20', 'Asta', 4),
('model-hyundai-i20-asta-o', 'make-hyundai', 'i20', 'Asta (O)', 5),
('model-hyundai-venue', 'make-hyundai', 'Venue', null, 100),
('model-hyundai-venue-e', 'make-hyundai', 'Venue', 'E', 101),
('model-hyundai-venue-s', 'make-hyundai', 'Venue', 'S', 102),
('model-hyundai-venue-s-o', 'make-hyundai', 'Venue', 'S (O)', 103),
('model-hyundai-venue-sx', 'make-hyundai', 'Venue', 'SX', 104),
('model-hyundai-venue-sx-o', 'make-hyundai', 'Venue', 'SX (O)', 105),
('model-hyundai-creta', 'make-hyundai', 'Creta', null, 200),
('model-hyundai-creta-e', 'make-hyundai', 'Creta', 'E', 201),
('model-hyundai-creta-ex', 'make-hyundai', 'Creta', 'EX', 202),
('model-hyundai-creta-s', 'make-hyundai', 'Creta', 'S', 203),
('model-hyundai-creta-sx', 'make-hyundai', 'Creta', 'SX', 204),
('model-hyundai-creta-sx-o', 'make-hyundai', 'Creta', 'SX (O)', 205),
('model-hyundai-verna', 'make-hyundai', 'Verna', null, 300),
('model-hyundai-verna-ex', 'make-hyundai', 'Verna', 'EX', 301),
('model-hyundai-verna-s', 'make-hyundai', 'Verna', 'S', 302),
('model-hyundai-verna-sx', 'make-hyundai', 'Verna', 'SX', 303),
('model-hyundai-verna-sx-o', 'make-hyundai', 'Verna', 'SX (O)', 304),
('model-hyundai-exter', 'make-hyundai', 'Exter', null, 400),
('model-hyundai-exter-ex', 'make-hyundai', 'Exter', 'EX', 401),
('model-hyundai-exter-s', 'make-hyundai', 'Exter', 'S', 402),
('model-hyundai-exter-sx', 'make-hyundai', 'Exter', 'SX', 403),
('model-hyundai-exter-sx-o', 'make-hyundai', 'Exter', 'SX (O)', 404),
('model-hyundai-grand-i10-nios', 'make-hyundai', 'Grand i10 Nios', null, 500),
('model-hyundai-grand-i10-nios-era', 'make-hyundai', 'Grand i10 Nios', 'Era', 501),
('model-hyundai-grand-i10-nios-magna', 'make-hyundai', 'Grand i10 Nios', 'Magna', 502),
('model-hyundai-grand-i10-nios-sportz', 'make-hyundai', 'Grand i10 Nios', 'Sportz', 503),
('model-hyundai-grand-i10-nios-asta', 'make-hyundai', 'Grand i10 Nios', 'Asta', 504),
('model-hyundai-aura', 'make-hyundai', 'Aura', null, 600),
('model-hyundai-aura-e', 'make-hyundai', 'Aura', 'E', 601),
('model-hyundai-aura-s', 'make-hyundai', 'Aura', 'S', 602),
('model-hyundai-aura-sx', 'make-hyundai', 'Aura', 'SX', 603),
('model-hyundai-aura-sx-o', 'make-hyundai', 'Aura', 'SX (O)', 604),
('model-hyundai-alcazar', 'make-hyundai', 'Alcazar', null, 700),
('model-hyundai-alcazar-prestige', 'make-hyundai', 'Alcazar', 'Prestige', 701),
('model-hyundai-alcazar-platinum', 'make-hyundai', 'Alcazar', 'Platinum', 702),
('model-hyundai-alcazar-signature', 'make-hyundai', 'Alcazar', 'Signature', 703),
('model-hyundai-tucson', 'make-hyundai', 'Tucson', null, 800),
('model-hyundai-tucson-signature', 'make-hyundai', 'Tucson', 'Signature', 801),
('model-hyundai-tucson-platinum', 'make-hyundai', 'Tucson', 'Platinum', 802),
('model-hyundai-santro', 'make-hyundai', 'Santro', null, 900),
('model-hyundai-santro-d-lite', 'make-hyundai', 'Santro', 'D-Lite', 901),
('model-hyundai-santro-era', 'make-hyundai', 'Santro', 'Era', 902),
('model-hyundai-santro-magna', 'make-hyundai', 'Santro', 'Magna', 903),
('model-hyundai-santro-sportz', 'make-hyundai', 'Santro', 'Sportz', 904),
('model-hyundai-santro-asta', 'make-hyundai', 'Santro', 'Asta', 905),
('model-tata-nexon', 'make-tata', 'Nexon', null, 0),
('model-tata-nexon-smart', 'make-tata', 'Nexon', 'Smart', 1),
('model-tata-nexon-pure', 'make-tata', 'Nexon', 'Pure', 2),
('model-tata-nexon-creative', 'make-tata', 'Nexon', 'Creative', 3),
('model-tata-nexon-fearless', 'make-tata', 'Nexon', 'Fearless', 4),
('model-tata-punch', 'make-tata', 'Punch', null, 100),
('model-tata-punch-pure', 'make-tata', 'Punch', 'Pure', 101),
('model-tata-punch-adventure', 'make-tata', 'Punch', 'Adventure', 102),
('model-tata-punch-accomplished', 'make-tata', 'Punch', 'Accomplished', 103),
('model-tata-punch-creative', 'make-tata', 'Punch', 'Creative', 104),
('model-tata-tiago', 'make-tata', 'Tiago', null, 200),
('model-tata-tiago-xe', 'make-tata', 'Tiago', 'XE', 201),
('model-tata-tiago-xm', 'make-tata', 'Tiago', 'XM', 202),
('model-tata-tiago-xt', 'make-tata', 'Tiago', 'XT', 203),
('model-tata-tiago-xz', 'make-tata', 'Tiago', 'XZ', 204),
('model-tata-tiago-xz-plus', 'make-tata', 'Tiago', 'XZ+', 205),
('model-tata-altroz', 'make-tata', 'Altroz', null, 300),
('model-tata-altroz-xe', 'make-tata', 'Altroz', 'XE', 301),
('model-tata-altroz-xm-plus', 'make-tata', 'Altroz', 'XM+', 302),
('model-tata-altroz-xt', 'make-tata', 'Altroz', 'XT', 303),
('model-tata-altroz-xz', 'make-tata', 'Altroz', 'XZ', 304),
('model-tata-altroz-xz-plus', 'make-tata', 'Altroz', 'XZ+', 305),
('model-tata-harrier', 'make-tata', 'Harrier', null, 400),
('model-tata-harrier-smart', 'make-tata', 'Harrier', 'Smart', 401),
('model-tata-harrier-pure', 'make-tata', 'Harrier', 'Pure', 402),
('model-tata-harrier-adventure', 'make-tata', 'Harrier', 'Adventure', 403),
('model-tata-harrier-fearless', 'make-tata', 'Harrier', 'Fearless', 404),
('model-tata-safari', 'make-tata', 'Safari', null, 500),
('model-tata-safari-smart', 'make-tata', 'Safari', 'Smart', 501),
('model-tata-safari-pure', 'make-tata', 'Safari', 'Pure', 502),
('model-tata-safari-adventure', 'make-tata', 'Safari', 'Adventure', 503),
('model-tata-safari-accomplished', 'make-tata', 'Safari', 'Accomplished', 504),
('model-tata-tigor', 'make-tata', 'Tigor', null, 600),
('model-tata-tigor-xe', 'make-tata', 'Tigor', 'XE', 601),
('model-tata-tigor-xm', 'make-tata', 'Tigor', 'XM', 602),
('model-tata-tigor-xz', 'make-tata', 'Tigor', 'XZ', 603),
('model-tata-tigor-xz-plus', 'make-tata', 'Tigor', 'XZ+', 604),
('model-tata-curvv', 'make-tata', 'Curvv', null, 700),
('model-tata-curvv-creative', 'make-tata', 'Curvv', 'Creative', 701),
('model-tata-curvv-accomplished', 'make-tata', 'Curvv', 'Accomplished', 702),
('model-tata-curvv-empowered', 'make-tata', 'Curvv', 'Empowered', 703),
('model-mahindra-scorpio-n', 'make-mahindra', 'Scorpio-N', null, 0),
('model-mahindra-scorpio-n-z2', 'make-mahindra', 'Scorpio-N', 'Z2', 1),
('model-mahindra-scorpio-n-z4', 'make-mahindra', 'Scorpio-N', 'Z4', 2),
('model-mahindra-scorpio-n-z6', 'make-mahindra', 'Scorpio-N', 'Z6', 3),
('model-mahindra-scorpio-n-z8', 'make-mahindra', 'Scorpio-N', 'Z8', 4),
('model-mahindra-scorpio-n-z8-l', 'make-mahindra', 'Scorpio-N', 'Z8 L', 5),
('model-mahindra-xuv700', 'make-mahindra', 'XUV700', null, 100),
('model-mahindra-xuv700-mx', 'make-mahindra', 'XUV700', 'MX', 101),
('model-mahindra-xuv700-ax3', 'make-mahindra', 'XUV700', 'AX3', 102),
('model-mahindra-xuv700-ax5', 'make-mahindra', 'XUV700', 'AX5', 103),
('model-mahindra-xuv700-ax7', 'make-mahindra', 'XUV700', 'AX7', 104),
('model-mahindra-xuv700-ax7-l', 'make-mahindra', 'XUV700', 'AX7 L', 105),
('model-mahindra-thar', 'make-mahindra', 'Thar', null, 200),
('model-mahindra-thar-ax', 'make-mahindra', 'Thar', 'AX', 201),
('model-mahindra-thar-ax-o', 'make-mahindra', 'Thar', 'AX (O)', 202),
('model-mahindra-thar-lx', 'make-mahindra', 'Thar', 'LX', 203),
('model-mahindra-bolero', 'make-mahindra', 'Bolero', null, 300),
('model-mahindra-bolero-b4', 'make-mahindra', 'Bolero', 'B4', 301),
('model-mahindra-bolero-b6', 'make-mahindra', 'Bolero', 'B6', 302),
('model-mahindra-bolero-b6-o', 'make-mahindra', 'Bolero', 'B6 (O)', 303),
('model-mahindra-xuv300', 'make-mahindra', 'XUV300', null, 400),
('model-mahindra-xuv300-w2', 'make-mahindra', 'XUV300', 'W2', 401),
('model-mahindra-xuv300-w4', 'make-mahindra', 'XUV300', 'W4', 402),
('model-mahindra-xuv300-w6', 'make-mahindra', 'XUV300', 'W6', 403),
('model-mahindra-xuv300-w8', 'make-mahindra', 'XUV300', 'W8', 404),
('model-mahindra-xuv300-w8-o', 'make-mahindra', 'XUV300', 'W8 (O)', 405),
('model-mahindra-scorpio-classic', 'make-mahindra', 'Scorpio Classic', null, 500),
('model-mahindra-scorpio-classic-s', 'make-mahindra', 'Scorpio Classic', 'S', 501),
('model-mahindra-scorpio-classic-s11', 'make-mahindra', 'Scorpio Classic', 'S11', 502),
('model-mahindra-xuv400', 'make-mahindra', 'XUV400', null, 600),
('model-mahindra-xuv400-ec', 'make-mahindra', 'XUV400', 'EC', 601),
('model-mahindra-xuv400-el', 'make-mahindra', 'XUV400', 'EL', 602),
('model-mahindra-bolero-neo', 'make-mahindra', 'Bolero Neo', null, 700),
('model-mahindra-bolero-neo-n4', 'make-mahindra', 'Bolero Neo', 'N4', 701),
('model-mahindra-bolero-neo-n8', 'make-mahindra', 'Bolero Neo', 'N8', 702),
('model-mahindra-bolero-neo-n10', 'make-mahindra', 'Bolero Neo', 'N10', 703),
('model-toyota-innova-crysta', 'make-toyota', 'Innova Crysta', null, 0),
('model-toyota-innova-crysta-gx', 'make-toyota', 'Innova Crysta', 'GX', 1),
('model-toyota-innova-crysta-vx', 'make-toyota', 'Innova Crysta', 'VX', 2),
('model-toyota-innova-crysta-zx', 'make-toyota', 'Innova Crysta', 'ZX', 3),
('model-toyota-innova-hycross', 'make-toyota', 'Innova Hycross', null, 100),
('model-toyota-innova-hycross-gx', 'make-toyota', 'Innova Hycross', 'GX', 101),
('model-toyota-innova-hycross-vx', 'make-toyota', 'Innova Hycross', 'VX', 102),
('model-toyota-innova-hycross-zx', 'make-toyota', 'Innova Hycross', 'ZX', 103),
('model-toyota-innova-hycross-zx-o', 'make-toyota', 'Innova Hycross', 'ZX (O)', 104),
('model-toyota-fortuner', 'make-toyota', 'Fortuner', null, 200),
('model-toyota-fortuner-4x2', 'make-toyota', 'Fortuner', '4x2', 201),
('model-toyota-fortuner-4x4', 'make-toyota', 'Fortuner', '4x4', 202),
('model-toyota-fortuner-legender', 'make-toyota', 'Fortuner', 'Legender', 203),
('model-toyota-glanza', 'make-toyota', 'Glanza', null, 300),
('model-toyota-glanza-e', 'make-toyota', 'Glanza', 'E', 301),
('model-toyota-glanza-s', 'make-toyota', 'Glanza', 'S', 302),
('model-toyota-glanza-g', 'make-toyota', 'Glanza', 'G', 303),
('model-toyota-glanza-v', 'make-toyota', 'Glanza', 'V', 304),
('model-toyota-urban-cruiser-hyryder', 'make-toyota', 'Urban Cruiser Hyryder', null, 400),
('model-toyota-urban-cruiser-hyryder-e', 'make-toyota', 'Urban Cruiser Hyryder', 'E', 401),
('model-toyota-urban-cruiser-hyryder-s', 'make-toyota', 'Urban Cruiser Hyryder', 'S', 402),
('model-toyota-urban-cruiser-hyryder-g', 'make-toyota', 'Urban Cruiser Hyryder', 'G', 403),
('model-toyota-urban-cruiser-hyryder-v', 'make-toyota', 'Urban Cruiser Hyryder', 'V', 404),
('model-toyota-rumion', 'make-toyota', 'Rumion', null, 500),
('model-toyota-rumion-s', 'make-toyota', 'Rumion', 'S', 501),
('model-toyota-rumion-g', 'make-toyota', 'Rumion', 'G', 502),
('model-toyota-rumion-v', 'make-toyota', 'Rumion', 'V', 503),
('model-toyota-camry', 'make-toyota', 'Camry', null, 600),
('model-toyota-camry-hybrid', 'make-toyota', 'Camry', 'Hybrid', 601),
('model-toyota-land-cruiser', 'make-toyota', 'Land Cruiser', null, 700),
('model-toyota-land-cruiser-vx', 'make-toyota', 'Land Cruiser', 'VX', 701),
('model-toyota-land-cruiser-zx', 'make-toyota', 'Land Cruiser', 'ZX', 702),
('model-kia-seltos', 'make-kia', 'Seltos', null, 0),
('model-kia-seltos-hte', 'make-kia', 'Seltos', 'HTE', 1),
('model-kia-seltos-htk', 'make-kia', 'Seltos', 'HTK', 2),
('model-kia-seltos-htk-plus', 'make-kia', 'Seltos', 'HTK+', 3),
('model-kia-seltos-htx', 'make-kia', 'Seltos', 'HTX', 4),
('model-kia-seltos-gtx-plus', 'make-kia', 'Seltos', 'GTX+', 5),
('model-kia-sonet', 'make-kia', 'Sonet', null, 100),
('model-kia-sonet-hte', 'make-kia', 'Sonet', 'HTE', 101),
('model-kia-sonet-htk', 'make-kia', 'Sonet', 'HTK', 102),
('model-kia-sonet-htk-plus', 'make-kia', 'Sonet', 'HTK+', 103),
('model-kia-sonet-htx', 'make-kia', 'Sonet', 'HTX', 104),
('model-kia-sonet-gtx-plus', 'make-kia', 'Sonet', 'GTX+', 105),
('model-kia-carens', 'make-kia', 'Carens', null, 200),
('model-kia-carens-premium', 'make-kia', 'Carens', 'Premium', 201),
('model-kia-carens-prestige', 'make-kia', 'Carens', 'Prestige', 202),
('model-kia-carens-luxury', 'make-kia', 'Carens', 'Luxury', 203),
('model-kia-carens-luxury-plus', 'make-kia', 'Carens', 'Luxury Plus', 204),
('model-kia-carnival', 'make-kia', 'Carnival', null, 300),
('model-kia-carnival-premium', 'make-kia', 'Carnival', 'Premium', 301),
('model-kia-carnival-prestige', 'make-kia', 'Carnival', 'Prestige', 302),
('model-kia-carnival-limousine', 'make-kia', 'Carnival', 'Limousine', 303),
('model-kia-ev6', 'make-kia', 'EV6', null, 400),
('model-kia-ev6-gt-line', 'make-kia', 'EV6', 'GT Line', 401),
('model-honda-city', 'make-honda', 'City', null, 0),
('model-honda-city-sv', 'make-honda', 'City', 'SV', 1),
('model-honda-city-v', 'make-honda', 'City', 'V', 2),
('model-honda-city-vx', 'make-honda', 'City', 'VX', 3),
('model-honda-city-zx', 'make-honda', 'City', 'ZX', 4),
('model-honda-amaze', 'make-honda', 'Amaze', null, 100),
('model-honda-amaze-e', 'make-honda', 'Amaze', 'E', 101),
('model-honda-amaze-s', 'make-honda', 'Amaze', 'S', 102),
('model-honda-amaze-vx', 'make-honda', 'Amaze', 'VX', 103),
('model-honda-elevate', 'make-honda', 'Elevate', null, 200),
('model-honda-elevate-sv', 'make-honda', 'Elevate', 'SV', 201),
('model-honda-elevate-v', 'make-honda', 'Elevate', 'V', 202),
('model-honda-elevate-vx', 'make-honda', 'Elevate', 'VX', 203),
('model-honda-elevate-zx', 'make-honda', 'Elevate', 'ZX', 204),
('model-honda-jazz', 'make-honda', 'Jazz', null, 300),
('model-honda-jazz-v', 'make-honda', 'Jazz', 'V', 301),
('model-honda-jazz-vx', 'make-honda', 'Jazz', 'VX', 302),
('model-renault-kwid', 'make-renault', 'Kwid', null, 0),
('model-renault-kwid-rxe', 'make-renault', 'Kwid', 'RXE', 1),
('model-renault-kwid-rxl', 'make-renault', 'Kwid', 'RXL', 2),
('model-renault-kwid-rxt', 'make-renault', 'Kwid', 'RXT', 3),
('model-renault-kwid-climber', 'make-renault', 'Kwid', 'Climber', 4),
('model-renault-triber', 'make-renault', 'Triber', null, 100),
('model-renault-triber-rxe', 'make-renault', 'Triber', 'RXE', 101),
('model-renault-triber-rxl', 'make-renault', 'Triber', 'RXL', 102),
('model-renault-triber-rxt', 'make-renault', 'Triber', 'RXT', 103),
('model-renault-triber-rxz', 'make-renault', 'Triber', 'RXZ', 104),
('model-renault-kiger', 'make-renault', 'Kiger', null, 200),
('model-renault-kiger-rxe', 'make-renault', 'Kiger', 'RXE', 201),
('model-renault-kiger-rxl', 'make-renault', 'Kiger', 'RXL', 202),
('model-renault-kiger-rxt', 'make-renault', 'Kiger', 'RXT', 203),
('model-renault-kiger-rxz', 'make-renault', 'Kiger', 'RXZ', 204),
('model-volkswagen-virtus', 'make-volkswagen', 'Virtus', null, 0),
('model-volkswagen-virtus-comfortline', 'make-volkswagen', 'Virtus', 'Comfortline', 1),
('model-volkswagen-virtus-highline', 'make-volkswagen', 'Virtus', 'Highline', 2),
('model-volkswagen-virtus-topline', 'make-volkswagen', 'Virtus', 'Topline', 3),
('model-volkswagen-virtus-gt-plus', 'make-volkswagen', 'Virtus', 'GT Plus', 4),
('model-volkswagen-taigun', 'make-volkswagen', 'Taigun', null, 100),
('model-volkswagen-taigun-comfortline', 'make-volkswagen', 'Taigun', 'Comfortline', 101),
('model-volkswagen-taigun-highline', 'make-volkswagen', 'Taigun', 'Highline', 102),
('model-volkswagen-taigun-topline', 'make-volkswagen', 'Taigun', 'Topline', 103),
('model-volkswagen-taigun-gt-plus', 'make-volkswagen', 'Taigun', 'GT Plus', 104),
('model-volkswagen-tiguan', 'make-volkswagen', 'Tiguan', null, 200),
('model-volkswagen-tiguan-elegance', 'make-volkswagen', 'Tiguan', 'Elegance', 201),
('model-skoda-slavia', 'make-skoda', 'Slavia', null, 0),
('model-skoda-slavia-active', 'make-skoda', 'Slavia', 'Active', 1),
('model-skoda-slavia-ambition', 'make-skoda', 'Slavia', 'Ambition', 2),
('model-skoda-slavia-style', 'make-skoda', 'Slavia', 'Style', 3),
('model-skoda-kushaq', 'make-skoda', 'Kushaq', null, 100),
('model-skoda-kushaq-active', 'make-skoda', 'Kushaq', 'Active', 101),
('model-skoda-kushaq-ambition', 'make-skoda', 'Kushaq', 'Ambition', 102),
('model-skoda-kushaq-style', 'make-skoda', 'Kushaq', 'Style', 103),
('model-skoda-octavia', 'make-skoda', 'Octavia', null, 200),
('model-skoda-octavia-style', 'make-skoda', 'Octavia', 'Style', 201),
('model-skoda-octavia-l-k', 'make-skoda', 'Octavia', 'L&K', 202),
('model-skoda-superb', 'make-skoda', 'Superb', null, 300),
('model-skoda-superb-style', 'make-skoda', 'Superb', 'Style', 301),
('model-skoda-superb-l-k', 'make-skoda', 'Superb', 'L&K', 302),
('model-skoda-kodiaq', 'make-skoda', 'Kodiaq', null, 400),
('model-skoda-kodiaq-style', 'make-skoda', 'Kodiaq', 'Style', 401),
('model-skoda-kodiaq-l-k', 'make-skoda', 'Kodiaq', 'L&K', 402),
('model-mg-hector', 'make-mg', 'Hector', null, 0),
('model-mg-hector-style', 'make-mg', 'Hector', 'Style', 1),
('model-mg-hector-smart', 'make-mg', 'Hector', 'Smart', 2),
('model-mg-hector-sharp', 'make-mg', 'Hector', 'Sharp', 3),
('model-mg-hector-savvy', 'make-mg', 'Hector', 'Savvy', 4),
('model-mg-astor', 'make-mg', 'Astor', null, 100),
('model-mg-astor-style', 'make-mg', 'Astor', 'Style', 101),
('model-mg-astor-super', 'make-mg', 'Astor', 'Super', 102),
('model-mg-astor-smart', 'make-mg', 'Astor', 'Smart', 103),
('model-mg-astor-sharp', 'make-mg', 'Astor', 'Sharp', 104),
('model-mg-astor-savvy', 'make-mg', 'Astor', 'Savvy', 105),
('model-mg-zs-ev', 'make-mg', 'ZS EV', null, 200),
('model-mg-zs-ev-excite', 'make-mg', 'ZS EV', 'Excite', 201),
('model-mg-zs-ev-exclusive', 'make-mg', 'ZS EV', 'Exclusive', 202),
('model-mg-comet-ev', 'make-mg', 'Comet EV', null, 300),
('model-mg-comet-ev-pace', 'make-mg', 'Comet EV', 'Pace', 301),
('model-mg-comet-ev-play', 'make-mg', 'Comet EV', 'Play', 302),
('model-mg-comet-ev-plush', 'make-mg', 'Comet EV', 'Plush', 303),
('model-mg-windsor-ev', 'make-mg', 'Windsor EV', null, 400),
('model-mg-windsor-ev-excite', 'make-mg', 'Windsor EV', 'Excite', 401),
('model-mg-windsor-ev-exclusive', 'make-mg', 'Windsor EV', 'Exclusive', 402),
('model-nissan-magnite', 'make-nissan', 'Magnite', null, 0),
('model-nissan-magnite-xe', 'make-nissan', 'Magnite', 'XE', 1),
('model-nissan-magnite-xl', 'make-nissan', 'Magnite', 'XL', 2),
('model-nissan-magnite-xv', 'make-nissan', 'Magnite', 'XV', 3),
('model-nissan-magnite-xv-premium', 'make-nissan', 'Magnite', 'XV Premium', 4),
('model-jeep-compass', 'make-jeep', 'Compass', null, 0),
('model-jeep-compass-sport', 'make-jeep', 'Compass', 'Sport', 1),
('model-jeep-compass-longitude', 'make-jeep', 'Compass', 'Longitude', 2),
('model-jeep-compass-limited', 'make-jeep', 'Compass', 'Limited', 3),
('model-jeep-compass-model-s', 'make-jeep', 'Compass', 'Model S', 4),
('model-jeep-meridian', 'make-jeep', 'Meridian', null, 100),
('model-jeep-meridian-longitude', 'make-jeep', 'Meridian', 'Longitude', 101),
('model-jeep-meridian-limited', 'make-jeep', 'Meridian', 'Limited', 102),
('model-jeep-meridian-overland', 'make-jeep', 'Meridian', 'Overland', 103),
('model-citroen-c3', 'make-citroen', 'C3', null, 0),
('model-citroen-c3-live', 'make-citroen', 'C3', 'Live', 1),
('model-citroen-c3-feel', 'make-citroen', 'C3', 'Feel', 2),
('model-citroen-c3-shine', 'make-citroen', 'C3', 'Shine', 3),
('model-citroen-c3-aircross', 'make-citroen', 'C3 Aircross', null, 100),
('model-citroen-c3-aircross-you', 'make-citroen', 'C3 Aircross', 'You', 101),
('model-citroen-c3-aircross-plus', 'make-citroen', 'C3 Aircross', 'Plus', 102),
('model-citroen-c3-aircross-max', 'make-citroen', 'C3 Aircross', 'Max', 103),
('model-citroen-basalt', 'make-citroen', 'Basalt', null, 200),
('model-citroen-basalt-plus', 'make-citroen', 'Basalt', 'Plus', 201),
('model-citroen-basalt-max', 'make-citroen', 'Basalt', 'Max', 202),
('model-byd-atto-3', 'make-byd', 'Atto 3', null, 0),
('model-byd-atto-3-superior', 'make-byd', 'Atto 3', 'Superior', 1),
('model-byd-seal', 'make-byd', 'Seal', null, 100),
('model-byd-seal-premium', 'make-byd', 'Seal', 'Premium', 101),
('model-byd-seal-performance', 'make-byd', 'Seal', 'Performance', 102),
('model-byd-e6', 'make-byd', 'e6', null, 200),
('model-mercedes-benz-a-class-limousine', 'make-mercedes-benz', 'A-Class Limousine', null, 0),
('model-mercedes-benz-a-class-limousine-progressive', 'make-mercedes-benz', 'A-Class Limousine', 'Progressive', 1),
('model-mercedes-benz-c-class', 'make-mercedes-benz', 'C-Class', null, 100),
('model-mercedes-benz-c-class-avantgarde', 'make-mercedes-benz', 'C-Class', 'Avantgarde', 101),
('model-mercedes-benz-c-class-amg-line', 'make-mercedes-benz', 'C-Class', 'AMG Line', 102),
('model-mercedes-benz-e-class', 'make-mercedes-benz', 'E-Class', null, 200),
('model-mercedes-benz-e-class-avantgarde', 'make-mercedes-benz', 'E-Class', 'Avantgarde', 201),
('model-mercedes-benz-e-class-amg-line', 'make-mercedes-benz', 'E-Class', 'AMG Line', 202),
('model-mercedes-benz-gla', 'make-mercedes-benz', 'GLA', null, 300),
('model-mercedes-benz-gla-progressive', 'make-mercedes-benz', 'GLA', 'Progressive', 301),
('model-mercedes-benz-gla-amg-line', 'make-mercedes-benz', 'GLA', 'AMG Line', 302),
('model-mercedes-benz-glc', 'make-mercedes-benz', 'GLC', null, 400),
('model-mercedes-benz-glc-avantgarde', 'make-mercedes-benz', 'GLC', 'Avantgarde', 401),
('model-mercedes-benz-glc-amg-line', 'make-mercedes-benz', 'GLC', 'AMG Line', 402),
('model-mercedes-benz-s-class', 'make-mercedes-benz', 'S-Class', null, 500),
('model-mercedes-benz-s-class-s-350d', 'make-mercedes-benz', 'S-Class', 'S 350d', 501),
('model-mercedes-benz-s-class-s-450', 'make-mercedes-benz', 'S-Class', 'S 450', 502),
('model-bmw-3-series', 'make-bmw', '3 Series', null, 0),
('model-bmw-3-series-sport-line', 'make-bmw', '3 Series', 'Sport Line', 1),
('model-bmw-3-series-luxury-line', 'make-bmw', '3 Series', 'Luxury Line', 2),
('model-bmw-3-series-m-sport', 'make-bmw', '3 Series', 'M Sport', 3),
('model-bmw-5-series', 'make-bmw', '5 Series', null, 100),
('model-bmw-5-series-sport-line', 'make-bmw', '5 Series', 'Sport Line', 101),
('model-bmw-5-series-luxury-line', 'make-bmw', '5 Series', 'Luxury Line', 102),
('model-bmw-5-series-m-sport', 'make-bmw', '5 Series', 'M Sport', 103),
('model-bmw-x1', 'make-bmw', 'X1', null, 200),
('model-bmw-x1-sdrive', 'make-bmw', 'X1', 'sDrive', 201),
('model-bmw-x1-xline', 'make-bmw', 'X1', 'xLine', 202),
('model-bmw-x1-m-sport', 'make-bmw', 'X1', 'M Sport', 203),
('model-bmw-x3', 'make-bmw', 'X3', null, 300),
('model-bmw-x3-xline', 'make-bmw', 'X3', 'xLine', 301),
('model-bmw-x3-m-sport', 'make-bmw', 'X3', 'M Sport', 302),
('model-bmw-x5', 'make-bmw', 'X5', null, 400),
('model-bmw-x5-xline', 'make-bmw', 'X5', 'xLine', 401),
('model-bmw-x5-m-sport', 'make-bmw', 'X5', 'M Sport', 402),
('model-audi-a4', 'make-audi', 'A4', null, 0),
('model-audi-a4-premium', 'make-audi', 'A4', 'Premium', 1),
('model-audi-a4-premium-plus', 'make-audi', 'A4', 'Premium Plus', 2),
('model-audi-a4-technology', 'make-audi', 'A4', 'Technology', 3),
('model-audi-a6', 'make-audi', 'A6', null, 100),
('model-audi-a6-premium', 'make-audi', 'A6', 'Premium', 101),
('model-audi-a6-premium-plus', 'make-audi', 'A6', 'Premium Plus', 102),
('model-audi-a6-technology', 'make-audi', 'A6', 'Technology', 103),
('model-audi-q3', 'make-audi', 'Q3', null, 200),
('model-audi-q3-premium', 'make-audi', 'Q3', 'Premium', 201),
('model-audi-q3-premium-plus', 'make-audi', 'Q3', 'Premium Plus', 202),
('model-audi-q3-technology', 'make-audi', 'Q3', 'Technology', 203),
('model-audi-q5', 'make-audi', 'Q5', null, 300),
('model-audi-q5-premium-plus', 'make-audi', 'Q5', 'Premium Plus', 301),
('model-audi-q5-technology', 'make-audi', 'Q5', 'Technology', 302),
('model-volvo-xc40', 'make-volvo', 'XC40', null, 0),
('model-volvo-xc40-momentum', 'make-volvo', 'XC40', 'Momentum', 1),
('model-volvo-xc40-inscription', 'make-volvo', 'XC40', 'Inscription', 2),
('model-volvo-xc40-ultimate', 'make-volvo', 'XC40', 'Ultimate', 3),
('model-volvo-xc60', 'make-volvo', 'XC60', null, 100),
('model-volvo-xc60-momentum', 'make-volvo', 'XC60', 'Momentum', 101),
('model-volvo-xc60-inscription', 'make-volvo', 'XC60', 'Inscription', 102),
('model-volvo-xc60-ultimate', 'make-volvo', 'XC60', 'Ultimate', 103),
('model-volvo-xc90', 'make-volvo', 'XC90', null, 200),
('model-volvo-xc90-momentum', 'make-volvo', 'XC90', 'Momentum', 201),
('model-volvo-xc90-inscription', 'make-volvo', 'XC90', 'Inscription', 202),
('model-volvo-xc90-ultimate', 'make-volvo', 'XC90', 'Ultimate', 203),
('model-land-rover-range-rover', 'make-land-rover', 'Range Rover', null, 0),
('model-land-rover-range-rover-se', 'make-land-rover', 'Range Rover', 'SE', 1),
('model-land-rover-range-rover-hse', 'make-land-rover', 'Range Rover', 'HSE', 2),
('model-land-rover-range-rover-autobiography', 'make-land-rover', 'Range Rover', 'Autobiography', 3),
('model-land-rover-range-rover-sport', 'make-land-rover', 'Range Rover Sport', null, 100),
('model-land-rover-range-rover-sport-se', 'make-land-rover', 'Range Rover Sport', 'SE', 101),
('model-land-rover-range-rover-sport-hse', 'make-land-rover', 'Range Rover Sport', 'HSE', 102),
('model-land-rover-range-rover-sport-autobiography', 'make-land-rover', 'Range Rover Sport', 'Autobiography', 103),
('model-land-rover-range-rover-evoque', 'make-land-rover', 'Range Rover Evoque', null, 200),
('model-land-rover-range-rover-evoque-s', 'make-land-rover', 'Range Rover Evoque', 'S', 201),
('model-land-rover-range-rover-evoque-se', 'make-land-rover', 'Range Rover Evoque', 'SE', 202),
('model-land-rover-range-rover-evoque-hse', 'make-land-rover', 'Range Rover Evoque', 'HSE', 203),
('model-land-rover-discovery-sport', 'make-land-rover', 'Discovery Sport', null, 300),
('model-land-rover-discovery-sport-s', 'make-land-rover', 'Discovery Sport', 'S', 301),
('model-land-rover-discovery-sport-se', 'make-land-rover', 'Discovery Sport', 'SE', 302),
('model-land-rover-discovery-sport-hse', 'make-land-rover', 'Discovery Sport', 'HSE', 303),
('model-land-rover-defender', 'make-land-rover', 'Defender', null, 400),
('model-land-rover-defender-90', 'make-land-rover', 'Defender', '90', 401),
('model-land-rover-defender-110', 'make-land-rover', 'Defender', '110', 402),
('model-land-rover-defender-130', 'make-land-rover', 'Defender', '130', 403),
('model-jaguar-xf', 'make-jaguar', 'XF', null, 0),
('model-jaguar-xf-prestige', 'make-jaguar', 'XF', 'Prestige', 1),
('model-jaguar-xf-portfolio', 'make-jaguar', 'XF', 'Portfolio', 2),
('model-jaguar-xf-r-dynamic', 'make-jaguar', 'XF', 'R-Dynamic', 3),
('model-jaguar-f-pace', 'make-jaguar', 'F-Pace', null, 100),
('model-jaguar-f-pace-prestige', 'make-jaguar', 'F-Pace', 'Prestige', 101),
('model-jaguar-f-pace-portfolio', 'make-jaguar', 'F-Pace', 'Portfolio', 102),
('model-jaguar-f-pace-r-dynamic', 'make-jaguar', 'F-Pace', 'R-Dynamic', 103),
('model-lexus-es', 'make-lexus', 'ES', null, 0),
('model-lexus-es-elegant', 'make-lexus', 'ES', 'Elegant', 1),
('model-lexus-es-luxury', 'make-lexus', 'ES', 'Luxury', 2),
('model-lexus-nx', 'make-lexus', 'NX', null, 100),
('model-lexus-nx-elegant', 'make-lexus', 'NX', 'Elegant', 101),
('model-lexus-nx-luxury', 'make-lexus', 'NX', 'Luxury', 102),
('model-lexus-nx-f-sport', 'make-lexus', 'NX', 'F Sport', 103),
('model-lexus-rx', 'make-lexus', 'RX', null, 200),
('model-lexus-rx-elegant', 'make-lexus', 'RX', 'Elegant', 201),
('model-lexus-rx-luxury', 'make-lexus', 'RX', 'Luxury', 202),
('model-lexus-rx-f-sport', 'make-lexus', 'RX', 'F Sport', 203),
('model-mini-cooper', 'make-mini', 'Cooper', null, 0),
('model-mini-cooper-classic', 'make-mini', 'Cooper', 'Classic', 1),
('model-mini-cooper-favoured', 'make-mini', 'Cooper', 'Favoured', 2),
('model-mini-countryman', 'make-mini', 'Countryman', null, 100),
('model-mini-countryman-classic', 'make-mini', 'Countryman', 'Classic', 101),
('model-mini-countryman-favoured', 'make-mini', 'Countryman', 'Favoured', 102),
('model-mini-countryman-jcw', 'make-mini', 'Countryman', 'JCW', 103),
('model-porsche-macan', 'make-porsche', 'Macan', null, 0),
('model-porsche-macan-base', 'make-porsche', 'Macan', 'Base', 1),
('model-porsche-macan-s', 'make-porsche', 'Macan', 'S', 2),
('model-porsche-macan-gts', 'make-porsche', 'Macan', 'GTS', 3),
('model-porsche-cayenne', 'make-porsche', 'Cayenne', null, 100),
('model-porsche-cayenne-base', 'make-porsche', 'Cayenne', 'Base', 101),
('model-porsche-cayenne-s', 'make-porsche', 'Cayenne', 'S', 102),
('model-porsche-cayenne-gts', 'make-porsche', 'Cayenne', 'GTS', 103),
('model-isuzu-d-max-v-cross', 'make-isuzu', 'D-Max V-Cross', null, 0),
('model-isuzu-d-max-v-cross-base', 'make-isuzu', 'D-Max V-Cross', 'Base', 1),
('model-isuzu-d-max-v-cross-z', 'make-isuzu', 'D-Max V-Cross', 'Z', 2),
('model-isuzu-mu-x', 'make-isuzu', 'MU-X', null, 100),
('model-isuzu-mu-x-base', 'make-isuzu', 'MU-X', 'Base', 101),
('model-isuzu-mu-x-z', 'make-isuzu', 'MU-X', 'Z', 102),
('model-force-motors-gurkha', 'make-force-motors', 'Gurkha', null, 0),
('model-force-motors-gurkha-5-door', 'make-force-motors', 'Gurkha', '5-Door', 1),
('model-force-motors-trax', 'make-force-motors', 'Trax', null, 100),
('model-force-motors-trax-cruiser', 'make-force-motors', 'Trax', 'Cruiser', 101),
('model-mitsubishi-pajero-sport', 'make-mitsubishi', 'Pajero Sport', null, 0),
('model-mitsubishi-pajero-sport-select-plus', 'make-mitsubishi', 'Pajero Sport', 'Select Plus', 1),
('model-mitsubishi-pajero-sport-select-plus-at', 'make-mitsubishi', 'Pajero Sport', 'Select Plus AT', 2),
('model-fiat-punto', 'make-fiat', 'Punto', null, 0),
('model-fiat-punto-active', 'make-fiat', 'Punto', 'Active', 1),
('model-fiat-punto-dynamic', 'make-fiat', 'Punto', 'Dynamic', 2),
('model-fiat-punto-emotion', 'make-fiat', 'Punto', 'Emotion', 3),
('model-fiat-linea', 'make-fiat', 'Linea', null, 100),
('model-fiat-linea-active', 'make-fiat', 'Linea', 'Active', 101),
('model-fiat-linea-dynamic', 'make-fiat', 'Linea', 'Dynamic', 102),
('model-fiat-linea-emotion', 'make-fiat', 'Linea', 'Emotion', 103),
('model-chevrolet-beat', 'make-chevrolet', 'Beat', null, 0),
('model-chevrolet-beat-ls', 'make-chevrolet', 'Beat', 'LS', 1),
('model-chevrolet-beat-lt', 'make-chevrolet', 'Beat', 'LT', 2),
('model-chevrolet-beat-ltz', 'make-chevrolet', 'Beat', 'LTZ', 3),
('model-chevrolet-spark', 'make-chevrolet', 'Spark', null, 100),
('model-chevrolet-spark-ls', 'make-chevrolet', 'Spark', 'LS', 101),
('model-chevrolet-spark-lt', 'make-chevrolet', 'Spark', 'LT', 102),
('model-chevrolet-cruze', 'make-chevrolet', 'Cruze', null, 200),
('model-chevrolet-cruze-lt', 'make-chevrolet', 'Cruze', 'LT', 201),
('model-chevrolet-cruze-ltz', 'make-chevrolet', 'Cruze', 'LTZ', 202),
('model-chevrolet-tavera', 'make-chevrolet', 'Tavera', null, 300),
('model-chevrolet-tavera-ls', 'make-chevrolet', 'Tavera', 'LS', 301),
('model-chevrolet-tavera-neo-3', 'make-chevrolet', 'Tavera', 'Neo 3', 302),
('model-datsun-go', 'make-datsun', 'GO', null, 0),
('model-datsun-go-d', 'make-datsun', 'GO', 'D', 1),
('model-datsun-go-a', 'make-datsun', 'GO', 'A', 2),
('model-datsun-go-t', 'make-datsun', 'GO', 'T', 3),
('model-datsun-redi-go', 'make-datsun', 'redi-GO', null, 100),
('model-datsun-redi-go-d', 'make-datsun', 'redi-GO', 'D', 101),
('model-datsun-redi-go-a', 'make-datsun', 'redi-GO', 'A', 102),
('model-datsun-redi-go-t', 'make-datsun', 'redi-GO', 'T', 103),
('model-premier-rio', 'make-premier', 'Rio', null, 0),
('model-premier-rio-nx', 'make-premier', 'Rio', 'NX', 1),
('model-premier-rio-gx', 'make-premier', 'Rio', 'GX', 2)
on conflict (id) do nothing;
