package com.hopcape.odo.core.data.fairness

import com.hopcape.odo.core.domain.fairness.model.OverchargeReport

/**
 * Local persistence for overcharge reports. Hides the SQLDelight database from
 * [OverchargeReportRepositoryImpl]: this owns deriving `owner_id` from the reported
 * service log and writing the row, the repository owns what an operation means (error
 * mapping, telemetry, asking for a sync).
 *
 * `owner_id` is taken from the parent service log rather than from the caller, mirroring
 * the server's `BEFORE INSERT` trigger (DB_SCHEMA §4): ownership is derived from the
 * record being reported, never asserted by the client. Reading the parent and inserting
 * the report happen in one transaction, so a log deleted in between cannot leave a report
 * pointing at nothing.
 *
 * Throws on storage failure; the repository turns that into a
 * `DomainError.PersistenceFailure`. Answers `false` — rather than throwing — when the
 * reported service log does not exist, which the repository reads as
 * `DomainError.ServiceLogNotFound`.
 */
internal interface OverchargeReportLocalDataSource {

    /** Insert [report] under [id], generated by the caller. */
    suspend fun insert(id: String, report: OverchargeReport): Boolean
}
