package com.hopcape.odo.core.data.reminder

import com.hopcape.odo.core.domain.car.model.CarId
import com.hopcape.odo.core.domain.owner.model.OwnerId
import com.hopcape.odo.core.domain.reminder.model.CustomReminder
import com.hopcape.odo.core.domain.reminder.model.ReminderDismissal
import com.hopcape.odo.core.domain.reminder.model.ReminderId
import kotlinx.coroutines.flow.Flow

/**
 * Local persistence for custom reminders and dismissals. Hides the SQLDelight database
 * from [ReminderRepositoryImpl]: this owns how rows are read and written (and, since a
 * row this build cannot read must never be guessed at, reports and drops one rather than
 * letting a bad cadence reach the feed), the repository owns what an operation means
 * (error mapping, telemetry for its own calls, asking for a sync).
 *
 * Write methods throw on storage failure; the repository turns that into a
 * `DomainError.PersistenceFailure`. The observe flows are raw — a read failure
 * propagates to the collector, and the repository decides how to report it.
 */
interface ReminderLocalDataSource {

    /** Insert [reminder] as a `PENDING` row. */
    suspend fun insert(reminder: CustomReminder)

    /**
     * Write [reminder] over its stored row and return it to `PENDING`. Answers `false`
     * when no live row with that id exists — checked in the same transaction as the
     * write, so a reminder deleted in between cannot turn into a silent no-op update.
     */
    suspend fun update(reminder: CustomReminder): Boolean

    /** Tombstone the reminder row. */
    suspend fun softDelete(id: ReminderId)

    /** Every live custom reminder for [carId], as it changes. */
    fun observeCustomByCar(carId: CarId): Flow<List<CustomReminder>>

    /** The custom reminder with [id], as it changes; `null` while no live row has that id. */
    fun observeById(id: ReminderId): Flow<CustomReminder?>

    /** Every recorded dismissal for [carId], as it changes. */
    fun observeDismissals(carId: CarId): Flow<List<ReminderDismissal>>

    /**
     * Record [dismissal] under [id], generated by the caller. Relies on `OR IGNORE` plus
     * the dismissal's unique index: dismissing the same occurrence twice finds the first
     * row already there and writes nothing.
     */
    suspend fun insertDismissal(id: String, carId: CarId, ownerId: OwnerId, dismissal: ReminderDismissal)
}
