package com.hopcape.logging.api

/**
 * The outbox of diagnostics requests the owner has made — one row per "send my logs", held
 * until the files it covers have actually been delivered.
 *
 * This exists because the request and the upload happen at different times. Somebody taps
 * send with no signal; WorkManager runs hours later; the process has died in between. The
 * reference quoted in their email has to survive all of that, or the code in the mail points
 * at nothing.
 *
 * A port, like [LogUploadTarget] and [LogFileStore]: this module knows what a request means,
 * and `:infrastructure:database` knows how to keep one. Nothing is bound on a build without
 * it, and [com.hopcape.logging.internal.upload.LogUploadCoordinator] then uploads with no
 * reference rather than refusing to upload.
 */
@StableLoggerApi
interface DiagnosticRequests {

    /**
     * Records a request the owner has just made. [reference] is what they were shown, so it
     * is generated by the caller ([DiagnosticReference]) rather than here — the code has to
     * exist before an upload does.
     */
    suspend fun open(reference: String, createdAtEpochMs: Long)

    /**
     * The oldest request still waiting for its files, or null when none is. Every file in
     * the pass that reads this is filed under it: a request means "the logs as they stood
     * when I asked", and that is every sealed file the device is still holding.
     */
    suspend fun oldestOpen(): String?

    /** Marks a request as covered — its pass delivered everything the device was holding. */
    suspend fun markDelivered(reference: String)

    /** Records a pass that left files behind, with whatever is known about why. */
    suspend fun markAttemptFailed(reference: String, error: String?)

    /** Forgets every request. Used when the account and its local data are erased. */
    suspend fun clearAll()
}
