package com.hopcape.odo.core.config.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSDeclaration
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asTypeName

/**
 * Writes the four generated pieces for one group, all into a single file beside the
 * interface that was written by hand.
 *
 * The hand-written interface is deliberately not generated. Generating it instead would
 * mean every call site referenced a type that does not exist until the first successful
 * build, so a fresh clone would be red in the IDE.
 */
internal class ConfigCodegen(private val codeGenerator: CodeGenerator) {

    fun generate(group: ParsedGroup) {
        val contribution = ClassName(group.packageName, "${group.simpleName}Contribution")
        val file = FileSpec.builder(group.packageName, "${group.simpleName}Generated")
            .addFileComment("Generated by :core:config:processor. Do not edit.")
            .addType(implementation(group, contribution))
            .addType(flows(group, contribution))
            .addType(contributionObject(group, contribution))
            .addProperty(koinModule(group, contribution))
            .build()

        codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, group.declaration.containingFile!!),
            packageName = group.packageName,
            fileName = "${group.simpleName}Generated",
        ).bufferedWriter().use(file::writeTo)
    }

    // ── <Name>Impl ────────────────────────────────────────────────────────────

    private fun implementation(group: ParsedGroup, contribution: ClassName): TypeSpec {
        val builder = TypeSpec.classBuilder("${group.simpleName}Impl")
            .addKdoc("The read-through implementation of [%T].", group.declaration.className())
            .addSuperinterface(group.declaration.className())
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter("resolver", CONFIG_RESOLVER)
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("resolver", CONFIG_RESOLVER, KModifier.PRIVATE)
                    .initializer("resolver")
                    .build(),
            )

        group.keys.forEach { key ->
            builder.addProperty(
                PropertySpec.builder(key.propertyName, key.typeName(), KModifier.OVERRIDE)
                    .getter(
                        FunSpec.getterBuilder()
                            .addStatement("return %L", key.read(contribution))
                            .build(),
                    )
                    .build(),
            )
        }
        return builder.build()
    }

    // ── <Name>Flows ───────────────────────────────────────────────────────────

    private fun flows(group: ParsedGroup, contribution: ClassName): TypeSpec {
        val builder = TypeSpec.classBuilder("${group.simpleName}Flows")
            .addKdoc(
                "One %T per key in [%T], for callers that should re-render when a fetch " +
                    "lands mid-session.",
                FLOW,
                group.declaration.className(),
            )
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter("resolver", CONFIG_RESOLVER)
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("resolver", CONFIG_RESOLVER, KModifier.PRIVATE)
                    .initializer("resolver")
                    .build(),
            )

        group.keys.forEach { key ->
            builder.addProperty(
                PropertySpec.builder(key.propertyName, FLOW.parameterizedBy(key.typeName()))
                    .initializer(key.readFlow(contribution))
                    .build(),
            )
        }
        return builder.build()
    }

    // ── <Name>Contribution ────────────────────────────────────────────────────

    private fun contributionObject(group: ParsedGroup, contribution: ClassName): TypeSpec {
        val builder = TypeSpec.objectBuilder(contribution)
            .addKdoc("The keys %L contributes to the registry.", group.simpleName)
            .addSuperinterface(CONFIG_CONTRIBUTION)
            .addProperty(
                PropertySpec.builder("GROUP", String::class, KModifier.CONST)
                    .initializer("%S", group.groupName)
                    .build(),
            )

        group.keys.forEach { key ->
            builder.addProperty(
                PropertySpec.builder(key.constantName(), String::class, KModifier.CONST)
                    .initializer("%S", key.key)
                    .build(),
            )
        }

        val keyList = CodeBlock.builder().add("listOf(\n").indent()
        group.keys.forEach { key -> keyList.add("%L,\n", key.descriptor()) }
        keyList.unindent().add(")")

        return builder
            .addProperty(
                PropertySpec.builder("groupName", String::class, KModifier.OVERRIDE)
                    .initializer("GROUP")
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("keys", LIST.parameterizedBy(CONFIG_KEY), KModifier.OVERRIDE)
                    .initializer(keyList.build())
                    .build(),
            )
            .build()
    }

    // ── the Koin module ───────────────────────────────────────────────────────

    private fun koinModule(group: ParsedGroup, contribution: ClassName): PropertySpec {
        val name = group.simpleName.replaceFirstChar(Char::lowercaseChar) + "Module"
        val body = CodeBlock.builder()
            .add("%M {\n", KOIN_MODULE)
            .indent()
            .addStatement(
                "single<%T> { %T(resolver = get()) }",
                group.declaration.className(),
                ClassName(group.packageName, "${group.simpleName}Impl"),
            )
            .addStatement("single { %T(resolver = get()) }", ClassName(group.packageName, "${group.simpleName}Flows"))
            // Not single<ConfigContribution> { … }: in Koin a second definition of the same
            // type replaces the first, so every group but one would silently vanish from
            // getAll<ConfigContribution>(). Binding a distinct primary type is the house
            // pattern, the same one the Syncable registrations use.
            .addStatement("single { %T } %M %T::class", contribution, KOIN_BIND, CONFIG_CONTRIBUTION)
            .unindent()
            .add("}")
            .build()

        return PropertySpec.builder(name, KOIN_MODULE_TYPE)
            .addKdoc(
                "Binds [%T], its flows, and its registry contribution. One line in `initKoin`.",
                group.declaration.className(),
            )
            .initializer(body)
            .build()
    }

    // ── per-key code ──────────────────────────────────────────────────────────

    private fun ParsedKey.typeName(): TypeName = when (type) {
        KeyType.BOOLEAN -> Boolean::class.asTypeName()
        KeyType.INT -> Int::class.asTypeName()
        KeyType.LONG -> Long::class.asTypeName()
        KeyType.DOUBLE -> Double::class.asTypeName()
        KeyType.STRING -> String::class.asTypeName()
        KeyType.ENUM -> enumDeclaration!!.className()
    }

    private fun ParsedKey.constantName(): String = key.uppercase()

    private fun ParsedKey.read(contribution: ClassName): CodeBlock = when (type) {
        KeyType.ENUM -> CodeBlock.of(
            "%T.valueOf(resolver.enumName(%T.%L))",
            enumDeclaration!!.className(),
            contribution,
            constantName(),
        )
        else -> CodeBlock.of("resolver.%L(%T.%L)", readerName(), contribution, constantName())
    }

    private fun ParsedKey.readFlow(contribution: ClassName): CodeBlock = when (type) {
        KeyType.ENUM -> CodeBlock.of(
            "resolver.enumNameFlow(%T.%L).%M { %T.valueOf(it) }",
            contribution,
            constantName(),
            FLOW_MAP,
            enumDeclaration!!.className(),
        )
        else -> CodeBlock.of("resolver.%LFlow(%T.%L)", readerName(), contribution, constantName())
    }

    private fun ParsedKey.readerName(): String = when (type) {
        KeyType.BOOLEAN -> "boolean"
        KeyType.INT -> "int"
        KeyType.LONG -> "long"
        KeyType.DOUBLE -> "double"
        KeyType.STRING -> "string"
        KeyType.ENUM -> "enumName"
    }

    private fun ParsedKey.descriptor(): CodeBlock {
        val builder = CodeBlock.builder()
            .add("%T(\n", CONFIG_KEY)
            .indent()
            .add("key = %L,\n", constantName())
            .add("type = %T.%L,\n", CONFIG_TYPE, type.name)
            .add("default = %L,\n", defaultLiteral)
            .add("owner = %S,\n", owner)
            .add("why = %S,\n", why)
        if (range != null) builder.add("range = %S,\n", range)
        if (type == KeyType.ENUM) {
            builder.add("enumValues = listOf(%L),\n", enumConstants.joinToString { "\"$it\"" })
        }
        return builder.unindent().add(")").build()
    }

    private companion object {
        val CONFIG_RESOLVER = ClassName(ConfigNames.PACKAGE, "ConfigResolver")
        val CONFIG_KEY = ClassName(ConfigNames.PACKAGE, "ConfigKey")
        val CONFIG_TYPE = ClassName(ConfigNames.PACKAGE, "ConfigType")
        val CONFIG_CONTRIBUTION = ClassName(ConfigNames.PACKAGE, "ConfigContribution")
        val FLOW = ClassName("kotlinx.coroutines.flow", "Flow")
        val FLOW_MAP = MemberName("kotlinx.coroutines.flow", "map")
        val LIST = ClassName("kotlin.collections", "List")
        val KOIN_MODULE = MemberName("org.koin.dsl", "module")
        val KOIN_BIND = MemberName("org.koin.dsl", "bind")
        val KOIN_MODULE_TYPE = ClassName("org.koin.core.module", "Module")
    }
}

/** Builds a [ClassName] without kotlinpoet-ksp, handling nested declarations. */
internal fun KSClassDeclaration.className(): ClassName {
    val names = mutableListOf<String>()
    var current: KSDeclaration? = this
    while (current is KSClassDeclaration) {
        names.add(0, current.simpleName.asString())
        current = current.parentDeclaration
    }
    return ClassName(packageName.asString(), names)
}
