-- Seed facts — growth plan ke hooks se, sab verifiable/public-knowledge claims.
-- Owner apne asli app numbers ke saath rows add/replace kare (stats jsonb me).

insert into social.content_bank (category, fact, stats, cta) values
('fine', 'PUC expire hone pe challan ₹10,000 tak ja sakta hai. Zyada tar logo ko apni expiry date yaad nahi hoti.',
 '[{"label":"CHALLAN","value":"₹10,000"},{"label":"CHECK TIME","value":"10 sec"}]', 'Apni date check karo — Odo'),
('fine', 'Insurance lapse = ₹2,000 fine, aur accident me claim ZERO. Renewal date phone me honi chahiye, dimaag me nahi.',
 '[{"label":"FINE","value":"₹2,000"},{"label":"CLAIM","value":"₹0"}]', 'Reminder lagao — Odo'),
('fine', 'RC, insurance, PUC — ye 3 documents gaadi me na hon to challan pakka hai. Digital copy 2 tap me dikha sakte ho.',
 '[{"label":"DOCUMENTS","value":"3"},{"label":"TAPS","value":"2"}]', 'Vault me rakho — Odo'),
('money_saved', 'Service wale "engine flush" jaise extra items likh dete hain jinki zaroorat nahi hoti. Apna service record ho to sawaal puch sakte ho.',
 '[{"label":"TYPICAL ADD-ON","value":"₹4,000"}]', 'Har bill track karo — Odo'),
('money_saved', 'Documented service record wali gaadi resale pe ₹20–40k zyada dila sakti hai. Buyer bharosa kharidta hai.',
 '[{"label":"EXTRA RESALE","value":"₹20–40k"}]', 'Record banao — Odo'),
('money_saved', 'Brochure wala mileage aur asli mileage alag hote hain. Tank-to-tank hisaab hi sach batata hai.',
 '[{"label":"FORMULA","value":"tank-to-tank"}]', 'Asli mileage jaano — Odo'),
('educational', 'Tyre ki depth check karne ka ₹1 ka tarika: coin ko groove me daalo. Border dikhe to tyre badalne ka time hai.',
 '[{"label":"COST","value":"₹1"},{"label":"TIME","value":"5 sec"}]', 'Gaadi ka dhyan — Odo'),
('educational', 'Used car khareedne se pehle service history sabse pehle maango. Jo bech raha hai record ke saath, wahi bharose layak hai.',
 null, 'Apna record ready rakho — Odo'),
('educational', 'Engine oil grade (5W-30 vs 10W-40) gaadi ke manual me likha hota hai — mechanic ki marzi pe mat chhodo.',
 null, 'Service details save karo — Odo'),
('seasonal', 'Kashmir ki sardi me battery sabse pehle deti hai. 3+ saal purani battery ho to season se pehle check karao.',
 '[{"label":"BATTERY LIFE","value":"3–5 saal"}]', 'Reminder lagao — Odo'),
('seasonal', 'Monsoon me wiper streak kare to ₹200 ka blade replacement kaafi hota (log poora assembly badalwa lete hain).',
 '[{"label":"ASLI FIX","value":"₹200"}]', 'Kharcha track karo — Odo'),
('resale', 'Bina record wali gaadi = shak. Record wali gaadi = bharosa. Bechne se 6 mahine pehle nahi, aaj se record rakho.',
 null, 'Aaj se shuru — Odo');

-- v2: 3 posts/day cadence ke liye bank badi ki (2026-08-17)
insert into social.content_bank (category, fact, stats, cta) values
('fine', 'Driving licence ki bhi expiry hoti hai — aur zyada tar logo ko renewal date yaad nahi rehti. Expired DL pe fine ₹5,000 tak.',
 '[{"label":"DL FINE","value":"₹5,000"}]', 'DL expiry yaad rakho — Odo'),
('money_saved', 'Har fuel fill note karo to pata chalta hai gaadi asli me kitna kha rahi hai. Zyada tar log andaze pe chalte hain.',
 '[{"label":"TRACKING","value":"per fill"}]', 'Fuel log rakho — Odo'),
('money_saved', 'Time pe service = engine ki lambi zindagi. Late service ka kharcha hamesha zyada nikalta hai.',
 null, 'Service reminder lagao — Odo'),
('educational', 'Coolant aur engine oil ki tarah brake fluid bhi expire hota hai — 2 saal me change recommend hota hai.',
 '[{"label":"BRAKE FLUID","value":"~2 saal"}]', 'Service history rakho — Odo'),
('educational', 'AC kam thanda kar raha hai? Pehle cabin filter check karao — ₹300 ka filter aksar ₹3,000 ki gas refill se bacha deta hai.',
 '[{"label":"FILTER","value":"₹300"},{"label":"GAS REFILL","value":"₹3,000"}]', 'Kharcha compare karo — Odo'),
('educational', 'Tyre pressure har 15 din me check karo — kam pressure = kam mileage + tyre ki jaldi maut.',
 '[{"label":"CHECK","value":"15 din"}]', 'Gaadi ka dhyan — Odo'),
('educational', 'Clutch ride karna (paon clutch pe rakh ke chalana) clutch plate ki life aadhi kar deta hai.',
 null, 'Repair kharcha track karo — Odo'),
('seasonal', 'Pahadi raaste pe mileage girna normal hai — AC + chadhai dono engine se zyada maangte hain.',
 null, 'Asli mileage jaano — Odo'),
('seasonal', 'Barish ke season me headlight/indicator ka check 2 minute ka hai — fog me yehi bachate hain.',
 null, 'Checklist banao — Odo'),
('resale', 'Buyer sabse pehle 2 cheezein maangta hai: service history aur accident record. Dono ready hon to bhaav tumhare haath me hai.',
 null, 'Record ready rakho — Odo'),
('resale', 'Gaadi ki value har saal girti hai, par maintained gaadi ki value SLOW girti hai. Records hi proof hain.',
 null, 'Proof banao — Odo'),
('fine', 'Third-party insurance minimum legal requirement hai — bina uske gaadi chalana seedha court challan hai.',
 null, 'Insurance date yaad rakho — Odo');
