import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    // Not `odo.kmp.library`: that convention exists to give a shared module the
    // Android and iOS targets, and this module has neither. It is a browser
    // application with its own entry point, the way :androidApp is an Android one.
    alias(libs.plugins.kotlinMultiplatform)
    // The Compose UI surface (runtime/foundation/ui/material3) and the @Preview
    // annotations, into commonMain. Wasm inherits them from there.
    alias(libs.plugins.odo.composeMultiplatform)
    // koin-core in commonMain, koin-test in commonTest. Same DI as every feature
    // module, so swapping the sample repositories for real ones is one file.
    alias(libs.plugins.odo.koin)
    // kotlin-test in commonTest. The URL round trip is the part of this module
    // that breaks silently — a link that parses but never formats is a page
    // nobody can reach — so it is the part with tests.
    alias(libs.plugins.odo.kmpTest)
    // The Firebase Auth REST payloads. Applied directly, the way :core:data and
    // :core:navigation do — there is nothing to configure beyond applying it.
    alias(libs.plugins.kotlinSerialization)
}

kotlin {
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser {
            commonWebpackConfig {
                // What index.html loads. Without this the bundle is named after the
                // Gradle module and the host page has to track a build detail.
                outputFileName = "odo-blog.js"
            }
            // Wasm has no host test runner the way Android and iOS do: the tests
            // run in a real browser or not at all. Headless Chrome is the one
            // every machine here already has.
            testTask {
                useKarma { useChromeHeadless() }
            }
        }
        // Produces the browser distribution that gets published under /blog.
        binaries.executable()
    }

    sourceSets {
        commonMain.dependencies {
            // The plumbing both web apps share: PostgREST, the Supabase session and
            // its Firebase exchange, the token store, and the presentation
            // primitives every ViewModel here is built out of.
            implementation(projects.webCore)
            // Either<WebError, T> on every repository call — the same shape the
            // app's ports have, so a Supabase implementation later reads like the
            // ones in :infrastructure:supabase rather than like a web experiment.
            implementation(libs.arrow.core)
            // viewModelScope, and the flows the ViewModels expose.
            implementation(libs.kotlinx.coroutines.core)
            // LocalDate on a post. Dates here are only ever displayed, but storing
            // them as text would put date formatting in the repository.
            implementation(libs.kotlinx.datetime)
            // koinViewModel() in the route hosts.
            implementation(libs.koin.composeViewmodel)
            // Firebase Auth over its REST API. No ContentNegotiation, matching
            // :infrastructure:supabase: the adapters decode with an explicit Json
            // so a non-2xx body is inspected before anything parses it as success.
            implementation(libs.ktor.client.core)
            implementation(libs.kotlinx.serialization.json)
        }
        val wasmJsMain by getting {
            dependencies {
                // window / document / history. Kotlin's stdlib carries no DOM
                // bindings on Wasm, so even mounting Compose needs this.
                implementation(libs.kotlinx.browser)
                // The engine. Picked up by `HttpClient { }` with no engine named,
                // because it is the only one on this module's classpath.
                implementation(libs.ktor.client.js)
            }
        }
        commonTest.dependencies {
            implementation(libs.kotlinx.coroutines.test)
            // MockEngine — drives the Firebase adapter without a network or a
            // Firebase project, the same way the Supabase adapters are tested.
            implementation(libs.ktor.client.mock)
        }
    }
}

// Compose Multiplatform string resources. Same rule as every feature module: no
// user-facing copy is written at a call site. `bl_` prefixes them, the way
// :feature:servicelog uses `sl_`.
compose.resources {
    publicResClass = false
    packageOfResClass = "com.hopcape.odo.web.blog.resources"
    generateResClass = always
}


// ── Supabase credentials ─────────────────────────────────────────────────────
// Generated by `:webCore:generateWebConfig` into `BuildWebConfig`, not here. Both
// web apps talk to the same project, so the task that reads `local.properties`
// belongs to the module they share rather than being copied into each of them.
